### ISSUE TITLE
CUDA Error encountered in bn_forward_cuda

### ISSUE THREAD

**Issue by MaxwellZWong** [liutinglt/CE2P#16]
Hi,

I have tried to run the test code, but it still raised a runtime error, as

> 0 images have been proceeded
test.py:128: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  prediction = net(Variable(torch.from_numpy(image_scale), volatile=True).cuda())
Traceback (most recent call last):
  File "test.py", line 208, in <module>
    main() 
  File "test.py", line 199, in main
    output = predict(model, image.numpy(), (np.asscalar(ori_size[0]), np.asscalar(ori_size[1])), is_mirror=args.is_mirror, scales=[1])
  File "test.py", line 128, in predict
    prediction = net(Variable(torch.from_numpy(image_scale), volatile=True).cuda())
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/xxx/CE2P/models.py", line 278, in forward
    x = self.bn1(x)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/xxx/CE2P/modules/bn.py", line 184, in forward
    self.activation, self.slope)
  File "/xxx/CE2P/modules/functions.py", line 218, in forward
    x, x, ctx.eps)
  File "/xxx/CE2P/modules/functions.py", line 16, in _check
    raise RuntimeError("CUDA Error encountered in {}".format(fn))
RuntimeError: CUDA Error encountered in <function CompiledLib.bn_forward_cuda at 0x7faf37cc8f28>

The configuration is: pytorch 0.4.0, CUDA 8.0, GPU P100.

Thanks,

**Comment by MaxwellZWong** [comment]
I am sorry for my fault that I forget to change the `CUDA_GENCODE`. When I changed it to `CUDA_GENCODE=-gencode=arch=compute_60,code=sm_60`, it works.
Thanks,
