### ISSUE TITLE
there are some problems when i test your  lip_149 model.

### ISSUE THREAD

**Issue by lxy443626128** [liutinglt/CE2P#22]
Traceback (most recent call last):
  File "evaluate.py", line 143, in <module>
    main()
  File "evaluate.py", line 122, in main
    state_dict_old = torch.load(restore_from)
  File "/export/home/###/anaconda3/envs/ce2p/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/export/home/####/anaconda3/envs/ce2p/lib/python3.6/site-packages/torch/serialization.py", line 549, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected -2900782209814488036 got 256

**Comment by liutinglt** [comment]
@lxy443626128 I haven't seen this error before. Maybe your file is corrupted. You can try to download the model again.

**Comment by lxy443626128** [comment]
@liutinglt thanks~ I have  download the model again and it works nows.
 And I find that the total loss function contain three parts, but in this project  the loss function just contain two parts for parsing and edge~
