### ISSUE TITLE
Getting error while running ./run_evaluate.sh 

### ISSUE THREAD

**Issue by saket-m** [liutinglt/CE2P#36]
Traceback (most recent call last):
  File "evaluate.py", line 6, in <module>
    from networks.CE2P import Res_Deeplab
  File "/home/saket/vision/semantic-segmentation/CE2P/networks/CE2P.py", line 13, in <module>
    from libs import InPlaceABN, InPlaceABNSync
  File "/home/saket/vision/semantic-segmentation/CE2P/libs/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNWrapper, InPlaceABNSync, InPlaceABNSyncWrapper
  File "/home/saket/vision/semantic-segmentation/CE2P/libs/bn.py", line 15, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/home/saket/vision/semantic-segmentation/CE2P/libs/functions.py", line 5, in <module>
    from . import _ext
  File "/home/saket/vision/semantic-segmentation/CE2P/libs/_ext/__init__.py", line 3, in <module>
    from .__ext import lib as _lib, ffi as _ffi
ImportError: /home/saket/vision/semantic-segmentation/CE2P/libs/_ext/__ext.so: undefined symbol: __cudaPopCallConfiguration

I've followed the steps mentioned in the README.md file and it seems I've not compiled the file properly.
I'm using pytorch 0.4.1.
Please help me.

**Comment by liutinglt** [comment]
I just test it on cuda 9.0,  you can try to use the same cuda version

**Comment by liutinglt** [comment]
@saket-m    I just test it on cuda 9.0,  you can try to use the same cuda version
