### ISSUE TITLE
How cam build "evluate.py"

### ISSUE THREAD

**Issue by ghost** [liutinglt/CE2P#45]
/home/mj/anaconda3/envs/CE2P/bin/python3.6 "/media/mj/MJ/01_MJ_PhD/ubuntu/CE2P-master (2)/evaluate.py"
Traceback (most recent call last):
  File "/media/mj/MJ/01_MJ_PhD/ubuntu/CE2P-master (2)/evaluate.py", line 6, in <module>
    from networks.CE2P import Res_Deeplab
  File "/media/mj/MJ/01_MJ_PhD/ubuntu/CE2P-master (2)/networks/CE2P.py", line 13, in <module>
    from libs import InPlaceABN, InPlaceABNSync
  File "/media/mj/MJ/01_MJ_PhD/ubuntu/CE2P-master (2)/libs/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNWrapper, InPlaceABNSync, InPlaceABNSyncWrapper
  File "/media/mj/MJ/01_MJ_PhD/ubuntu/CE2P-master (2)/libs/bn.py", line 15, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/media/mj/MJ/01_MJ_PhD/ubuntu/CE2P-master (2)/libs/functions.py", line 5, in <module>
    from . import _ext
  File "/media/mj/MJ/01_MJ_PhD/ubuntu/CE2P-master (2)/libs/_ext/__init__.py", line 3, in <module>
    from .__ext import lib as _lib, ffi as _ffi
ImportError: /media/mj/MJ/01_MJ_PhD/ubuntu/CE2P-master (2)/libs/_ext/__ext.so: undefined symbol: __cudaPopCallConfiguration

**Comment by eng100200** [comment]
did you solve this?
